---
title: "writing_functions"
author: "Xicheng Xie"
date: "2022-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(rvest)
```

```{r}
set.seed(1)
```

# My first function
```{r}
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  z
  
}

```

## let's have multiple outputs

```{r}
mean_and_sd = function(x){
  mean_x=mean(x)
  sd_x=sd(x)
  
  tibble(
    mean=mean_x,
    sd=sd_x
  )
}
```

## let's start with simulations
```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}
```


## let's write a fucntion to get reviews
```{r}
read_page_reviews = function(url){
  dynamite_html = read_html(url)

  review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

  review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

  review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()%>% 
  str_subset("The media could not be loaded.", negate = TRUE) %>% 
  str_subset("^$", negate = TRUE)

  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  ) 
  
}
```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

dynamite_reviews = bind_rows(
  read_page_reviews(vec_urls[1]),
  read_page_reviews(vec_urls[2]),
  read_page_reviews(vec_urls[3]),
  read_page_reviews(vec_urls[4]),
  read_page_reviews(vec_urls[5])
)

dynamite_reviews
```



